from medipet.hospital.data_source import FakeHospitalDataSource
from medipet.hospital.fake import FakeHospitalFailurePlan, FakeHospitalOperations
from medipet.hospital.operations import (
    ActionReceipt,
    Appointment,
    AppointmentNotCancellableError,
    AppointmentSlot,
    CancelAppointmentAction,
    CreateAppointmentAction,
    Department,
    Doctor,
    GetAppointmentQuery,
    GetHospitalQuery,
    Hospital,
    HospitalDataError,
    HospitalNotFoundError,
    HospitalOperations,
    HospitalOperationsError,
    HospitalUnavailableError,
    IdempotencyConflictError,
    InvalidHospitalRequestError,
    ListAppointmentsQuery,
    ListDepartmentsQuery,
    ListDoctorsQuery,
    SearchSlotsQuery,
    SlotUnavailableError,
)

__all__ = [
    "ActionReceipt",
    "Appointment",
    "AppointmentNotCancellableError",
    "AppointmentSlot",
    "CancelAppointmentAction",
    "CreateAppointmentAction",
    "Department",
    "Doctor",
    "FakeHospitalDataSource",
    "FakeHospitalFailurePlan",
    "FakeHospitalOperations",
    "GetAppointmentQuery",
    "GetHospitalQuery",
    "Hospital",
    "HospitalDataError",
    "HospitalNotFoundError",
    "HospitalOperations",
    "HospitalOperationsError",
    "HospitalUnavailableError",
    "IdempotencyConflictError",
    "InvalidHospitalRequestError",
    "ListAppointmentsQuery",
    "ListDepartmentsQuery",
    "ListDoctorsQuery",
    "SearchSlotsQuery",
    "SlotUnavailableError",
]
